service: aws-email-subscription-service
frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'
  region: ${self:provider.region}
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs18.x
  stage: dev
  profile: serverless-admin
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
        - Effect: Allow
          Action:
            - "s3:*"
          Resource: "*" 
        - Effect: Allow
          Action: SNS:Publish
          Resource: !Ref FactsMessages
  environment:
    USERS_TABLE: ${self:custom.tableName}
    REGION: ${self:provider.region}
    
functions:
  facts:
    handler: handler/getFacts.getFacts
    events:
      - http:
          path: facts
          method: get 
          cors: true
  add:
    handler: handler/addSubscriber.addSubscriber
    events:
      - http:
          path: subscribe
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

    FactsMessages:
      Type: AWS::SNS::Topic 
      Properties:
        # Create a topic to be subscribed to
        TopicName: facts-messages-${self:provider.stage}
    FactsMessagesSubscription:
      Type: AWS::SNS::Subscription
      Properties: 
        DeliveryPolicy: Json
        Endpoint: String

